# build: conda env create -f environment.yaml
# update: conda env update -f environment.yaml
name: neu-nbv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - pip:
      - pyhocon
      - opencv-python
      - dotmap
      - tensorboard
      - imageio
      - imageio-ffmpeg
      - ipdb
      - PyQt5
      - pretrainedmodels
      - lpips
      - torch-tb-profiler
      - matplotlib==3.6.2
      - kornia
      - open3d
      - scipy
      - click
      - torchmetrics
      - torchinfo
      - numpy
      - seaborn
      - pandas==1.5.0
  - pytorch==1.12.0
  - scipy
  - torchvision==0.13.0
  - scikit-image==0.17.2
  - tqdm
  - rospkg
  - gcc
